### ISSUE TITLE
stream_get_contents() expects parameter 1 to be resource, integer given

### ISSUE THREAD

**Issue by fede91it** [hamburgscleanest/guzzle-advanced-throttle#14] opened 2018-09-03 16:42 UTC
Using your client instead of Guzzle's one I got that error at each request.

Using native Guzzle client, always it work.

Why?

**Comment by Chroma91** [comment] 2018-09-03 17:11
I need more information to answer that. It could be something simple (e.g. PHP version too old).
If you provide a code example and your PHP version, I might be able to pin it down.

**Comment by fede91it** [comment] 2018-09-04 13:18
```php
$options = [
	'base_uri' => 'https://api.entstix.com/api/v1/xlive/',
	'headers' => [
		'Accept-Language' => 'en',
	],
	'auth' => ['username', 'password'],
];

$stack = HandlerStack::create();
$client = GuzzleThrottle::client(array_merge($options, ['handler' => $stack]);

$response = $client->get('content/attraction');

echo $response->getBody()->getContents();
```

and the result is

![image](https://user-images.githubusercontent.com/346224/45033679-80897180-b055-11e8-8879-edccc78a7660.png)

but, changing

```php
$client = GuzzleThrottle::client(array_merge($options, ['handler' => $stack]);
```

in

```php
$client = new \GuzzleHttp\Client(array_merge($options, ['handler' => $stack]);
```

get everything works fine

**Comment by fede91it** [comment] 2018-09-04 14:04
I'm running on laravel/homestead latest version

**Comment by Chroma91** [comment] 2018-09-04 14:10
Ah, so you are using the Laravel wrapper. There might be a problem with how you initialize the handler stack. Maybe you can try it with `new HandlerStack()` instead of `HandlerStack::create()` (I don't know if it makes a difference, though). Another thing to try first would be to see if it makes a difference to pass the array directly instead of using `array_merge`.

But I'll have a look this evening when I'm home. Shouldn't be that hard to find the issue :)

**Comment by fede91it** [comment] 2018-09-04 14:15
Thank you

Yes I tried with the bridge and without, with array merge and without (no issue here) and with new HandlerStack or with HandlerStack::create (same issue)

The only thing get things work is use the standard Guzzle Client. Adding the throttle middlewere get things broke.

**Comment by fede91it** [comment] 2018-09-04 14:40
Sure

```php
<?php

// @codeCoverageIgnoreStart

// example configuration
return [
    'cache' => [
        // Name of the configured driver in the Laravel cache config file / Also needs to be set when "no-cache" is set! Because it's used for the internal timers
        'driver' => env('CACHE_DRIVER'),
        // Cache strategy: no-cache, cache, force-cache
        'strategy' => 'force-cache',
        // TTL in minutes
        'ttl' => 900,
    ],
    'rules' => [
        // host (including scheme)
        'https://api.getyourguide.com' => [
            [
                // maximum number of requests in the given interval
                'max_requests' => 600,
                // interval in seconds till the limit is reset
                'request_interval' => 60,
            ],
        ],
        /**
         * @see https://mail.mixmax.com/m/sjn5eJw7arzyEEW4Z
         */
        'https://prelive.viatorapi.viator.com' => [
            [
                'max_requests' => 15,
                'request_interval' => 10,
            ],
        ],
        /**
         * @see https://mail.mixmax.com/m/sjn5eJw7arzyEEW4Z
         */
        'https://viatorapi.viator.com' => [
            [
                'max_requests' => 45,
                'request_interval' => 10,
            ],
        ],
    ],
];

// @codeCoverageIgnoreEnd
```

**Comment by Chroma91** [comment] 2018-09-04 20:38
I think it is a problem with the authorization. If I use your exact configuration with another endpoint that doesn't require auth it works perfectly. I don't have permission to access `https://api.entstix.com/api/v1/xlive/`. 

I can set up an environment that requires authentication tomorrow and check what the root cause is.

**Comment by fede91it** [comment] 2018-09-05 04:41
Thank you

Let me know if you need that auth credentials

**Comment by Chroma91** [comment] 2018-09-06 21:45
I just had another look at it. I think the stream is at a wrong position and not rewinded correctly in that case.

Can you try to get the contents with `echo (string) $response->getBody(); ` and report back what it returns?

**Comment by Chroma91** [comment] 2018-09-07 15:51
`getBody` will always return the whole response body, see https://guzzle3.readthedocs.io/http-client/response.html#response-body

`getContents` returns the response body from the current position of the stream/file pointer.

I'll create a new issue for that later when I'm home. But I won't be able to fix that behavior before next week, sorry.

**Comment by fede91it** [comment] 2018-09-08 05:07
Ouch, thanks for the explanation!

**Comment by Chroma91** [comment] 2018-09-15 11:07
Doesn't seem like an easy fix. 
The logging middleware has similar problems (see https://github.com/guzzle/guzzle/issues/1582). 

Gonna close this for now.

**Closed by Chroma91** 2018-09-15 11:07 UTC

**Comment by fede91it** [comment] 2018-09-15 15:29
Okay

The casting anyway solved my problem
